[general]
import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]
working_directory = "D:"

[terminal]
shell = {program = "E:/Git/bin/bash.exe", args = ["-i", "-l"]}

[window]
dimensions = {columns = 180, lines = 42}
position = {x = 45, y = 35}
padding = {x = 5, y = 10}
opacity = 0.97
blur = true

[font]
normal = { family = "Consolas Nerd Font Mono", style = "Regular" }
